import { FoodItem, Address, ExtraAddOn } from './types';

export const FOOD_ITEMS: FoodItem[] = [
  // --- BURGERS (9 items) ---
  {
    id: 'b1',
    name: 'Royal Angus Beef',
    description: 'Triple-stacked premium Angus beef, melted cheddar, caramelized onions, and truffle aioli.',
    price: 18.50,
    rating: 4.9,
    calories: '680 Kcal',
    time: '15-20 Min',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=800',
    category: 'Burger',
    ingredients: ['🥩', '🧀', '🧅', '🍄'],
    allergens: ['milk', 'gluten'],
    tags: ['savory', 'heavy', 'mild']
  },
  {
    id: 'b2',
    name: 'Spicy Zinger',
    description: 'Crispy fried chicken breast with jalapeños, pepper jack cheese, and habanero mayo.',
    price: 14.00,
    rating: 4.7,
    calories: '550 Kcal',
    time: '12-15 Min',
    image: 'https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?auto=format&fit=crop&q=80&w=600',
    category: 'Burger',
    ingredients: ['🍗', '🌶️', '🧀', '🥬'],
    allergens: ['milk', 'gluten', 'eggs'],
    tags: ['spicy', 'savory']
  },
  {
    id: 'b3',
    name: 'Garden Harvest',
    description: 'House-made chickpea & sweet potato patty, avocado, and vegan lemon aioli. Egg-free & Dairy-free.',
    price: 15.00,
    rating: 4.6,
    calories: '380 Kcal',
    time: '15 Min',
    image: 'https://images.unsplash.com/photo-1525059696034-4967a8e1dca2?auto=format&fit=crop&q=80&w=600',
    category: 'Burger',
    ingredients: ['🥑', '🍠', '🥬'],
    allergens: ['gluten'],
    tags: ['vegan', 'mild', 'healthy', 'egg-free']
  },
  {
    id: 'b4',
    name: 'Wagyu Truffle Gold',
    description: 'Aged Wagyu beef, gold-leaf truffle shavings, gruyere, and balsamic reduction. Egg-free bun available.',
    price: 28.00,
    rating: 5.0,
    calories: '710 Kcal',
    time: '20 Min',
    image: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?auto=format&fit=crop&q=80&w=600',
    category: 'Burger',
    ingredients: ['🥩', '🍄', '🧀'],
    allergens: ['milk', 'gluten'],
    tags: ['savory', 'heavy', 'premium', 'egg-free']
  },
  {
    id: 'b5',
    name: 'Umami Truffle Burger',
    description: 'Beef patty, shiitake mushrooms, miso glaze, and truffle butter. Absolutely no eggs.',
    price: 19.50,
    rating: 4.9,
    calories: '640 Kcal',
    time: '18 Min',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&q=80&w=600',
    category: 'Burger',
    ingredients: ['🥩', '🍄', '🧂'],
    allergens: ['milk', 'gluten'],
    tags: ['savory', 'umami', 'egg-free']
  },
  {
    id: 'b6',
    name: 'Korean BBQ Crunch',
    description: 'Glazed pork belly, kimchi slaw, and gochujang aioli on a toasted brioche.',
    price: 17.00,
    rating: 4.8,
    calories: '720 Kcal',
    time: '15 Min',
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&q=80&w=600',
    category: 'Burger',
    ingredients: ['🥩', '🥬', '🌶️'],
    allergens: ['gluten', 'soy'],
    tags: ['spicy', 'savory', 'bold']
  },
  {
    id: 'b7',
    name: 'Mediterranean Lamb',
    description: 'Spiced lamb patty, whipped feta, cucumber raita, and pickled red onions. Egg-free.',
    price: 21.00,
    rating: 4.7,
    calories: '590 Kcal',
    time: '18 Min',
    image: 'https://images.unsplash.com/photo-1547584370-2cc98b8b8dc8?auto=format&fit=crop&q=80&w=600',
    category: 'Burger',
    ingredients: ['🐑', '🧀', '🥒'],
    allergens: ['milk', 'gluten'],
    tags: ['savory', 'fresh', 'egg-free']
  },
  {
    id: 'b8',
    name: 'Crispy Buffalo Chicken',
    description: 'Hand-breaded chicken thigh tossed in frank\'s red hot with blue cheese dressing.',
    price: 15.50,
    rating: 4.6,
    calories: '610 Kcal',
    time: '12 Min',
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&q=80&w=600',
    category: 'Burger',
    ingredients: ['🍗', '🌶️', '🧀'],
    allergens: ['milk', 'gluten', 'eggs'],
    tags: ['spicy', 'bold']
  },
  {
    id: 'b9',
    name: 'Beyond Master Veggie',
    description: '100% plant-based Beyond Meat patty, vegan cheddar, and house relish. Egg-free.',
    price: 16.50,
    rating: 4.8,
    calories: '450 Kcal',
    time: '15 Min',
    image: 'https://images.unsplash.com/photo-1585238342024-78d387f4a707?auto=format&fit=crop&q=80&w=600',
    category: 'Burger',
    ingredients: ['🌱', '🧀', '🥬'],
    allergens: ['gluten'],
    tags: ['vegan', 'healthy', 'egg-free']
  },

  // --- PIZZAS (8 items) ---
  {
    id: 'p1',
    name: 'Truffle Mushroom Pizza',
    description: 'Wild forest mushrooms, truffle oil, fresh mozzarella, and aromatic thyme.',
    price: 26.00,
    rating: 4.9,
    calories: '920 Kcal',
    time: '20-25 Min',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=600',
    category: 'Pizza',
    ingredients: ['🍄', '🧀', '🌿'],
    allergens: ['milk', 'gluten'],
    tags: ['savory', 'mild']
  },
  {
    id: 'p2',
    name: 'Inferno Volcano',
    description: 'Extra spicy nduja, spicy salami, chili flakes, and ghost pepper honey.',
    price: 24.00,
    rating: 4.8,
    calories: '890 Kcal',
    time: '20 Min',
    image: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?auto=format&fit=crop&q=80&w=600',
    category: 'Pizza',
    ingredients: ['🍕', '🌶️', '🥩'],
    allergens: ['milk', 'gluten'],
    tags: ['extra spicy', 'bold']
  },
  {
    id: 'p3',
    name: 'Classic Margherita',
    description: 'Traditional Neapolitan pizza with DOP San Marzano tomatoes, buffalo mozzarella, and fresh basil.',
    price: 19.00,
    rating: 4.9,
    calories: '780 Kcal',
    time: '15 Min',
    image: 'https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?auto=format&fit=crop&q=80&w=800',
    category: 'Pizza',
    ingredients: ['🍅', '🧀', '🌿'],
    allergens: ['milk', 'gluten'],
    tags: ['savory', 'mild', 'vegetarian', 'egg-free']
  },
  {
    id: 'p4',
    name: 'Prosciutto di Parma',
    description: 'Thinly sliced prosciutto, arugula, shaved parmesan, and a balsamic glaze.',
    price: 25.00,
    rating: 4.9,
    calories: '850 Kcal',
    time: '18 Min',
    image: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?auto=format&fit=crop&q=80&w=600',
    category: 'Pizza',
    ingredients: ['🥩', '🌿', '🧀'],
    allergens: ['milk', 'gluten'],
    tags: ['savory', 'premium', 'egg-free']
  },
  {
    id: 'p5',
    name: 'Pesto Chicken Pizza',
    description: 'Roasted chicken breast, house-made basil pesto, cherry tomatoes, and pine nuts.',
    price: 22.00,
    rating: 4.7,
    calories: '810 Kcal',
    time: '20 Min',
    image: 'https://images.unsplash.com/photo-1511689660979-10d2b1aada49?auto=format&fit=crop&q=80&w=600',
    category: 'Pizza',
    ingredients: ['🌿', '🍗', '🍅'],
    allergens: ['milk', 'gluten', 'nuts'],
    tags: ['savory', 'fresh', 'egg-free']
  },
  {
    id: 'p6',
    name: 'BBQ Smoked Chicken',
    description: 'Hickory BBQ sauce, smoked chicken strips, red onions, and cilantro.',
    price: 23.50,
    rating: 4.8,
    calories: '880 Kcal',
    time: '20 Min',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=600',
    category: 'Pizza',
    ingredients: ['🍗', '🧅', '🥫'],
    allergens: ['milk', 'gluten'],
    tags: ['savory', 'smoky', 'egg-free']
  },
  {
    id: 'p7',
    name: 'White Truffle Cream',
    description: 'Rich bechamel sauce, white truffle oil, roasted garlic, and fontina cheese.',
    price: 27.00,
    rating: 5.0,
    calories: '940 Kcal',
    time: '22 Min',
    image: 'https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?auto=format&fit=crop&q=80&w=600',
    category: 'Pizza',
    ingredients: ['🧀', '🍄', '🧄'],
    allergens: ['milk', 'gluten'],
    tags: ['savory', 'heavy', 'egg-free']
  },
  {
    id: 'p8',
    name: 'Garden Supreme Pizza',
    description: 'Roasted peppers, artichokes, olives, baby spinach, and vegan mozzarella.',
    price: 20.00,
    rating: 4.6,
    calories: '710 Kcal',
    time: '18 Min',
    image: 'https://images.unsplash.com/photo-1590947132387-155cc02f3212?auto=format&fit=crop&q=80&w=600',
    category: 'Pizza',
    ingredients: ['🫑', '🥬', '🫒'],
    allergens: ['gluten'],
    tags: ['vegan', 'healthy', 'egg-free']
  },

  // --- PASTA (7 items) ---
  {
    id: 'ps1',
    name: 'Creamy Carbonara',
    description: 'Silky egg yolk sauce, crispy guanciale, pecorino romano, and black pepper.',
    price: 21.00,
    rating: 4.9,
    calories: '720 Kcal',
    time: '15 Min',
    image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?auto=format&fit=crop&q=80&w=600',
    category: 'Pasta',
    ingredients: ['🍝', '🥚', '🥩', '🧀'],
    allergens: ['eggs', 'milk', 'gluten'],
    tags: ['savory', 'heavy', 'classic']
  },
  {
    id: 'ps2',
    name: 'Smoked Chicken Alfredo',
    description: 'Hand-smoked chicken breast over fettuccine tossed in a 24-month aged parmesan cream.',
    price: 22.50,
    rating: 4.9,
    calories: '840 Kcal',
    time: '18 Min',
    image: 'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?auto=format&fit=crop&q=80&w=600',
    category: 'Pasta',
    ingredients: ['🍝', '🍗', '🧀', '🥛'],
    allergens: ['milk', 'gluten'],
    tags: ['savory', 'heavy', 'comfort', 'egg-free']
  },
  {
    id: 'ps3',
    name: 'Wild Mushroom Tagliatelle',
    description: 'Porcini and cremini mushrooms, white wine, garlic, and fresh parsley. Egg-free pasta.',
    price: 20.00,
    rating: 4.8,
    calories: '550 Kcal',
    time: '15 Min',
    image: 'https://images.unsplash.com/photo-1473093226795-af9932fe5856?auto=format&fit=crop&q=80&w=600',
    category: 'Pasta',
    ingredients: ['🍝', '🍄', '🌿'],
    allergens: ['gluten'],
    tags: ['savory', 'vegetarian', 'egg-free']
  },
  {
    id: 'ps4',
    name: 'Lobster Mac & Cheese',
    description: 'Maine lobster chunks, five-cheese Mornay sauce, and a herb breadcrumb crust.',
    price: 29.00,
    rating: 5.0,
    calories: '910 Kcal',
    time: '20 Min',
    image: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&q=80&w=600',
    category: 'Pasta',
    ingredients: ['🍝', '🦐', '🧀'],
    allergens: ['milk', 'gluten', 'shellfish'],
    tags: ['savory', 'premium', 'heavy']
  },
  {
    id: 'ps5',
    name: 'Pesto Gnocchi',
    description: 'Potato dumplings tossed in Genovese pesto, cherry tomatoes, and toasted pine nuts.',
    price: 18.50,
    rating: 4.7,
    calories: '620 Kcal',
    time: '12 Min',
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&q=80&w=600',
    category: 'Pasta',
    ingredients: ['🍝', '🌿', '🥜'],
    allergens: ['milk', 'gluten', 'nuts'],
    tags: ['savory', 'vegetarian', 'egg-free']
  },
  {
    id: 'ps6',
    name: 'Beef Ragu Lasagna',
    description: 'Layers of hand-made pasta, slow-cooked beef ragu, bechamel, and mozzarella.',
    price: 24.00,
    rating: 4.9,
    calories: '860 Kcal',
    time: '25 Min',
    image: 'https://images.unsplash.com/photo-1622973536968-3ead9e780960?auto=format&fit=crop&q=80&w=600',
    category: 'Pasta',
    ingredients: ['🍝', '🥩', '🧀'],
    allergens: ['milk', 'gluten', 'eggs'],
    tags: ['savory', 'classic']
  },
  {
    id: 'ps7',
    name: 'Spaghetti Aglio e Olio',
    description: 'Extra virgin olive oil, garlic confit, red chili flakes, and toasted crumbs. Vegan & Egg-free.',
    price: 16.00,
    rating: 4.6,
    calories: '410 Kcal',
    time: '10 Min',
    image: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?auto=format&fit=crop&q=80&w=600',
    category: 'Pasta',
    ingredients: ['🍝', '🧄', '🌶️'],
    allergens: ['gluten'],
    tags: ['vegan', 'spicy', 'egg-free']
  },

  // --- SALAD (7 items) ---
  {
    id: 's1',
    name: 'Classic Caesar',
    description: 'Crisp romaine heart, sourdough croutons, creamy parmesan dressing, and grilled chicken.',
    price: 16.50,
    rating: 4.8,
    calories: '320 Kcal',
    time: '10 Min',
    image: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?auto=format&fit=crop&q=80&w=600',
    category: 'Salad',
    ingredients: ['🥬', '🍗', '🍞', '🧀'],
    allergens: ['milk', 'gluten', 'eggs'],
    tags: ['fresh', 'healthy', 'mild']
  },
  {
    id: 's2',
    name: 'Greek Village Salad',
    description: 'Heirloom tomatoes, cucumber, kalamata olives, feta cheese, and dried oregano. Egg-free.',
    price: 14.00,
    rating: 4.7,
    calories: '280 Kcal',
    time: '8 Min',
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&q=80&w=600',
    category: 'Salad',
    ingredients: ['🍅', '🥒', '🫒', '🧀'],
    allergens: ['milk'],
    tags: ['fresh', 'vegetarian', 'healthy', 'egg-free']
  },
  {
    id: 's3',
    name: 'Quinoa & Pomegranate',
    description: 'Red quinoa, fresh mint, cucumber, pomegranate seeds, and a lemon tahini dressing.',
    price: 17.50,
    rating: 4.9,
    calories: '340 Kcal',
    time: '10 Min',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=600',
    category: 'Salad',
    ingredients: ['🥣', '🥒', '🍎'],
    allergens: ['sesame'],
    tags: ['vegan', 'healthy', 'egg-free']
  },
  {
    id: 's4',
    name: 'Steak & Gorgonzola',
    description: 'Sliced grilled sirloin, mixed greens, blue cheese crumbles, and walnuts.',
    price: 21.00,
    rating: 4.8,
    calories: '510 Kcal',
    time: '15 Min',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=600',
    category: 'Salad',
    ingredients: ['🥩', '🥬', '🧀'],
    allergens: ['milk', 'nuts'],
    tags: ['savory', 'heavy', 'egg-free']
  },
  {
    id: 's5',
    name: 'Asian Sesame Slaw',
    description: 'Shredded cabbage, carrots, edamame, and a toasted sesame ginger dressing. Egg-free.',
    price: 13.50,
    rating: 4.7,
    calories: '250 Kcal',
    time: '10 Min',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=600',
    category: 'Salad',
    ingredients: ['🥬', '🫘', '🥜'],
    allergens: ['soy', 'sesame'],
    tags: ['vegan', 'fresh', 'egg-free']
  },
  {
    id: 's6',
    name: 'Watermelon & Feta',
    description: 'Fresh watermelon cubes, feta, fresh mint, and a drizzle of lime oil. Perfect for summer.',
    price: 15.00,
    rating: 4.9,
    calories: '190 Kcal',
    time: '8 Min',
    image: 'https://images.unsplash.com/photo-1543362906-acfc16c67564?auto=format&fit=crop&q=80&w=600',
    category: 'Salad',
    ingredients: ['🍉', '🧀', '🌿'],
    allergens: ['milk'],
    tags: ['fresh', 'vegetarian', 'egg-free']
  },
  {
    id: 's7',
    name: 'Kale & Roasted Squash',
    description: 'Massage kale, roasted butternut squash, dried cranberries, and pumpkin seeds.',
    price: 18.00,
    rating: 4.7,
    calories: '420 Kcal',
    time: '12 Min',
    image: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&q=80&w=600',
    category: 'Salad',
    ingredients: ['🥬', '🎃', '🍎'],
    allergens: [],
    tags: ['vegan', 'healthy', 'egg-free']
  },

  // --- BREAKFAST (6 items) ---
  {
    id: 'br1',
    name: 'Velvet Pancakes',
    description: 'Fluffy buttermilk pancakes topped with fresh berries and whipped honey butter.',
    price: 13.50,
    rating: 4.8,
    calories: '520 Kcal',
    time: '10 Min',
    image: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&q=80&w=600',
    category: 'Breakfast',
    ingredients: ['🥞', '🍓', '🍯'],
    allergens: ['milk', 'eggs', 'gluten'],
    tags: ['sweet', 'mild']
  },
  {
    id: 'br2',
    name: 'Vanilla Bean Brioche Toast',
    description: 'Thick-cut artisan brioche soaked in premium Madagascan vanilla custard and seared with gold sugar.',
    price: 15.50,
    rating: 4.9,
    calories: '620 Kcal',
    time: '12 Min',
    image: 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?auto=format&fit=crop&q=80&w=800',
    category: 'Breakfast',
    ingredients: ['🍞', '🥚', '🍯'],
    allergens: ['milk', 'eggs', 'gluten'],
    tags: ['sweet', 'heavy']
  },
  {
    id: 'br4',
    name: 'Smoked Salmon Croissant',
    description: 'Buttery flaky croissant filled with wild smoked salmon, caper cream cheese, and dill.',
    price: 16.50,
    rating: 4.9,
    calories: '480 Kcal',
    time: '8 Min',
    image: 'https://images.unsplash.com/photo-1513442542250-854d436a73f2?auto=format&fit=crop&q=80&w=600',
    category: 'Breakfast',
    ingredients: ['🥐', '🐟', '🧀'],
    allergens: ['milk', 'gluten', 'fish'],
    tags: ['savory', 'fresh', 'egg-free']
  },
  {
    id: 'br5',
    name: 'Mexican Breakfast Bowl',
    description: 'Black beans, avocado, pico de gallo, its healthy flavor is unbeatable.',
    price: 14.50,
    rating: 4.7,
    calories: '510 Kcal',
    time: '15 Min',
    image: 'https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?auto=format&fit=crop&q=80&w=600',
    category: 'Breakfast',
    ingredients: ['🥑', '🫘', '🍚'],
    allergens: [],
    tags: ['fresh', 'healthy', 'spicy']
  },
  {
    id: 'br6',
    name: 'Tofu Scramble Power',
    description: 'Turmeric-spiced tofu, sautéed kale, roasted peppers, and sourdough. 100% Egg-free.',
    price: 15.00,
    rating: 4.6,
    calories: '390 Kcal',
    time: '12 Min',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=600',
    category: 'Breakfast',
    ingredients: ['🌱', '🥬', '🍞'],
    allergens: ['soy', 'gluten'],
    tags: ['vegan', 'healthy', 'egg-free']
  },
  {
    id: 'br7',
    name: 'Shakshuka Duo',
    description: 'Two poached eggs in a vibrant tomato and bell pepper sauce with toasted pita.',
    price: 15.50,
    rating: 4.9,
    calories: '420 Kcal',
    time: '15 Min',
    image: 'https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&q=80&w=600',
    category: 'Breakfast',
    ingredients: ['🥚', '🍅', '🫓'],
    allergens: ['eggs', 'gluten'],
    tags: ['savory', 'spicy']
  },

  // --- ICE CREAM (8 items) ---
  {
    id: 'ic1',
    name: 'Madagascan Vanilla Bean',
    description: 'Triple-churned organic cream infused with authentic Madagascar vanilla beans.',
    price: 6.50,
    rating: 5.0,
    calories: '220 Kcal',
    time: '3 Min',
    image: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?auto=format&fit=crop&q=80&w=800',
    category: 'Ice Cream',
    ingredients: ['🍦', '🥛'],
    allergens: ['milk'],
    tags: ['sweet', 'cold', 'dessert']
  },
  {
    id: 'ic2',
    name: 'Belgian Double Chocolate',
    description: 'Rich dark chocolate ice cream with swirls of Belgian fudge and chocolate chunks.',
    price: 7.50,
    rating: 4.9,
    calories: '310 Kcal',
    time: '3 Min',
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&q=80&w=600',
    category: 'Ice Cream',
    ingredients: ['🍫', '🥛'],
    allergens: ['milk'],
    tags: ['sweet', 'extra sweet', 'heavy']
  },
  {
    id: 'ic3',
    name: 'Sicilian Pistachio',
    description: 'Creamy pistachio base made with 100% roasted Sicilian pistachios.',
    price: 8.50,
    rating: 4.8,
    calories: '280 Kcal',
    time: '3 Min',
    image: 'https://images.unsplash.com/photo-1534706936160-d5ee67737249?auto=format&fit=crop&q=80&w=600',
    category: 'Ice Cream',
    ingredients: ['🥜', '🥛'],
    allergens: ['milk', 'nuts'],
    tags: ['sweet', 'savory', 'premium']
  },
  {
    id: 'ic4',
    name: 'Salted Caramel Ribbon',
    description: 'Buttery caramel ice cream with thick ribbons of hand-crafted salted caramel.',
    price: 7.00,
    rating: 4.9,
    calories: '290 Kcal',
    time: '3 Min',
    image: 'https://images.unsplash.com/photo-1543258103-a62bdc069871?auto=format&fit=crop&q=80&w=800',
    category: 'Ice Cream',
    ingredients: ['🍯', '🥛'],
    allergens: ['milk'],
    tags: ['sweet', 'savory', 'cold']
  },
  {
    id: 'ic6',
    name: 'Midnight Espresso',
    description: 'Strong Italian espresso-infused ice cream with dark chocolate shavings.',
    price: 7.00,
    rating: 4.9,
    calories: '240 Kcal',
    time: '3 Min',
    image: 'https://images.unsplash.com/photo-1557142046-c704a3adf364?auto=format&fit=crop&q=80&w=600',
    category: 'Ice Cream',
    ingredients: ['☕', '🥛'],
    allergens: ['milk'],
    tags: ['sweet', 'bitter', 'coffee']
  },
  {
    id: 'ic7',
    name: 'Lavender Honey Dream',
    description: 'Dried culinary lavender and organic clover honey in a silky cream base.',
    price: 8.00,
    rating: 4.8,
    calories: '260 Kcal',
    time: '3 Min',
    image: 'https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?auto=format&fit=crop&q=80&w=600',
    category: 'Ice Cream',
    ingredients: ['🍯', '🥛', '🌿'],
    allergens: ['milk'],
    tags: ['sweet', 'floral', 'premium']
  },
  {
    id: 'ic8',
    name: 'Dark Chocolate Sorbet',
    description: 'Deep, rich 70% cocoa sorbet. No dairy, no eggs, just pure indulgence.',
    price: 8.00,
    rating: 5.0,
    calories: '210 Kcal',
    time: '3 Min',
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&q=80&w=600',
    category: 'Ice Cream',
    ingredients: ['🍫'],
    allergens: [],
    tags: ['vegan', 'bold', 'egg-free']
  },
  {
    id: 'ic9',
    name: 'Wild Berry Swirl',
    description: 'Vanilla cream with a tart raspberry and blackberry reduction swirl.',
    price: 7.50,
    rating: 4.7,
    calories: '230 Kcal',
    time: '3 Min',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&q=80&w=600',
    category: 'Ice Cream',
    ingredients: ['🍓', '🥛'],
    allergens: ['milk'],
    tags: ['sweet', 'sour', 'fresh']
  },

// --- DESSERT (2 item) ---
  {
    id: 'ds1',
    name: 'Red Velvet Cream Cake',
    description: 'Signature vibrant red cocoa sponge layered with thick Madagascar vanilla cream cheese frosting.',
    price: 9.50,
    rating: 4.9,
    calories: '420 Kcal',
    time: '5 Min',
    image: 'https://images.unsplash.com/photo-1616031037011-087000171abe?auto=format&fit=crop&q=80&w=800',
    category: 'Dessert',
    ingredients: ['🍰', '🥛', '🍫'],
    allergens: ['milk', 'gluten', 'eggs'],
    tags: ['sweet', 'dessert', 'rich']
  },
  {
    id: 'ds8',
    name: 'Carrot & Walnut Cake',
    description: 'Spiced carrot sponge with roasted walnuts and a citrus-infused cream cheese frosting.',
    price: 8.50,
    rating: 4.8,
    calories: '390 Kcal',
    time: '5 Min',
    image: 'https://images.unsplash.com/photo-1533910534207-90f31029a78e?auto=format&fit=crop&q=80&w=800',
    category: 'Dessert',
    ingredients: ['🍰', '🥕', '🥜'],
    allergens: ['milk', 'gluten', 'eggs', 'nuts'],
    tags: ['sweet', 'nutty', 'dessert']
  },

  // --- SODAS (8 items) ---
  {
    id: 'sd1',
    name: 'Vintage Craft Cola',
    description: 'Small-batch cola with hints of vanilla, cinnamon, and real kola nut extract.',
    price: 4.50,
    rating: 4.7,
    calories: '150 Kcal',
    time: '2 Min',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=800',
    category: 'Soda',
    ingredients: ['🥤'],
    allergens: [],
    tags: ['sweet', 'carbonated', 'cold']
  },
  {
    id: 'sd2',
    name: 'Wild Cherry Sparkle',
    description: 'Crisp sparkling water infused with fresh black cherry nectar and natural fizz.',
    price: 4.50,
    rating: 4.6,
    calories: '130 Kcal',
    time: '2 Min',
    image: 'https://images.unsplash.com/photo-1527661591475-527312dd65f5?auto=format&fit=crop&q=80&w=600',
    category: 'Soda',
    ingredients: ['🥤', '🍒'],
    allergens: [],
    tags: ['sweet', 'refreshing', 'carbonated']
  },
  {
    id: 'sd3',
    name: 'Zesty Lemon Lime',
    description: 'Ultra-refreshing citrus blend made with cold-pressed lemon and lime oils.',
    price: 4.00,
    rating: 4.5,
    calories: '110 Kcal',
    time: '2 Min',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=600',
    category: 'Soda',
    ingredients: ['🥤', '🍋'],
    allergens: [],
    tags: ['sour', 'refreshing', 'cold']
  },
  {
    id: 'sd5',
    name: 'Craft Root Beer',
    description: 'Traditional root beer brewed with sarsaparilla, anise, and local honey.',
    price: 5.00,
    rating: 4.9,
    calories: '170 Kcal',
    time: '2 Min',
    image: 'https://images.unsplash.com/photo-1581006852262-e4307cf6283a?auto=format&fit=crop&q=80&w=600',
    category: 'Soda',
    ingredients: ['🥤', '🍯'],
    allergens: [],
    tags: ['sweet', 'spiced', 'cold']
  },
  {
    id: 'sd6',
    name: 'Pineapple Hibiscus',
    description: 'Tropical pineapple juice blended with tart hibiscus tea and carbonation.',
    price: 5.00,
    rating: 4.7,
    calories: '140 Kcal',
    time: '2 Min',
    image: 'https://images.unsplash.com/photo-1497515114629-f71d768fd07c?auto=format&fit=crop&q=80&w=600',
    category: 'Soda',
    ingredients: ['🥤', '🍍', '🌿'],
    allergens: [],
    tags: ['sweet', 'floral', 'fresh']
  },
  {
    id: 'sd7',
    name: 'Ginger Lemon Zing',
    description: 'Real ginger root pressed with lemon for a spicy, gut-healthy kick.',
    price: 5.50,
    rating: 4.8,
    calories: '90 Kcal',
    time: '2 Min',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=600',
    category: 'Soda',
    ingredients: ['🥤', '🫚', '🍋'],
    allergens: [],
    tags: ['spicy', 'healthy', 'fresh']
  },
  {
    id: 'sd8',
    name: 'Creamy Peach Soda',
    description: 'Sun-ripened peach flavor with a touch of vanilla cream. Refreshingly smooth.',
    price: 4.50,
    rating: 4.6,
    calories: '150 Kcal',
    time: '2 Min',
    image: 'https://images.unsplash.com/photo-1527661591475-527312dd65f5?auto=format&fit=crop&q=80&w=600',
    category: 'Soda',
    ingredients: ['🥤', '🍑'],
    allergens: [],
    tags: ['sweet', 'fresh']
  },
  {
    id: 'sd9',
    name: 'Grapefruit Blush',
    description: 'Tart Ruby Red grapefruit with a splash of rosemary syrup and sparkling water.',
    price: 5.00,
    rating: 4.7,
    calories: '100 Kcal',
    time: '2 Min',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=600',
    category: 'Soda',
    ingredients: ['🥤', '🍊', '🌿'],
    allergens: [],
    tags: ['sour', 'fresh', 'bitter']
  }
];

export const CATEGORIES = [
  { name: 'All', icon: '✨' },
  { name: 'Burger', icon: '🍔' },
  { name: 'Pizza', icon: '🍕' },
  { name: 'Pasta', icon: '🍝' },
  { name: 'Salad', icon: '🥗' },
  { name: 'Breakfast', icon: '🍳' },
  { name: 'Ice Cream', icon: '🍦' },
  { name: 'Dessert', icon: '🍰' },
  { name: 'Soda', icon: '🥤' },
];

export const ADDRESSES: Address[] = [
  { id: 'addr-1', type: 'Home', address: 'Sadia Villa, Habiganj, 3300', phone: '(875) 878-785' },
  { id: 'addr-2', type: 'Office', address: '8301 Elgin St. Habiganj, 3300', phone: '(217) 555-0113' },
];

export const EXTRA_MEAL_INGREDIENTS: ExtraAddOn[] = [
  { id: 'ex1', name: 'Extra Cheese', price: 1.50, icon: '🧀' },
  { id: 'ex2', name: 'Avocado', price: 2.00, icon: '🥑' },
  { id: 'ex3', name: 'Fried Egg', price: 1.25, icon: '🍳' },
  { id: 'ex4', name: 'Maple Bacon', price: 2.50, icon: '🥓' },
  { id: 'ex5', name: 'Extra Patty', price: 5.00, icon: '🥩' },
  { id: 'ex6', name: 'Truffle Mayo', price: 1.00, icon: '🍄' },
];

export const EXTRA_DRINK_INGREDIENTS: ExtraAddOn[] = [
  { id: 'dex1', name: 'Extra Espresso', price: 1.50, icon: '☕' },
  { id: 'dex2', name: 'Vanilla Syrup', price: 0.75, icon: '🍯' },
  { id: 'dex3', name: 'Oat Milk', price: 1.00, icon: '🥛' },
  { id: 'dex4', name: 'Whipped Cream', price: 0.50, icon: '☁️' },
  { id: 'dex5', name: 'Crushed Ice', price: 0.25, icon: '🧊' },
];

export const EXTRA_ICECREAM_INGREDIENTS: ExtraAddOn[] = [
  { id: 'ix1', name: 'Rainbow Sprinkles', price: 0.50, icon: '🌈' },
  { id: 'ix2', name: 'Warm Hot Fudge', price: 1.50, icon: '🍫' },
  { id: 'ix3', name: 'Crushed Oreos', price: 1.00, icon: '🍪' },
  { id: 'ix4', name: 'Waffle Cone', price: 2.00, icon: '🍦' },
  { id: 'ix5', name: 'Maraschino Cherry', price: 0.50, icon: '🍒' },
  { id: 'ix6', name: 'Caramel Drizzle', price: 0.75, icon: '🍯' },
];
